language: objective-c
osx_image: xcode8
before_install:
  - brew update
  - brew install carthage
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap
script:
  - xcodebuild test -scheme VideoMarks -sdk iphonesimulator -destination "name=iPhone SE"
